config/routes.rb
Nucleus::Application.routes.draw do

  resources :projects do
      resources :tasks
  end

  devise_for :users

  
  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  accepts_nested_attributes_for :users, :allow_destroy => true
  validates_presence_of :name, :desc, :cost, :deadline, :category
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :projects
  accepts_nested_attributes_for :projects, :allow_destroy => true
  has_many :authored_projects, :class_name => "Project", :foreign_key => "author_id"
  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery
	include ApplicationHelper
	layout :layout_by_resource

 	 def layout_by_resource
   	 	if devise_controller? && resource_name == :user && action_name == 'new'
   	 		"devise"
   	 	else
     	 	"application"
   	 	end
 	 end

 	 def after_sign_in_path_for(resource_name = :user)
        root_path
     end
	
end

app/controllers/home_controller.rb
class HomeController <  ApplicationController

  def index
  	if user_signed_in?
    	@projects = current_user.projects.all
    	@own_projects = current_user.authored_projects.all
    	if @projects.empty? && @own_projects.empty?
    		render  'empty'
    	end
	else
		render 'home'
	end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.authored_projects.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.authored_projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create

    @project =  Project.find(params[:project_id])
    @task = @project.tasks.new(params[:task])
    user = User.find(params[:task][:user_id])
    user.projects << @project unless user.projects.include?(@project)
    @task.status = "initial"
    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { redirect_to @project }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def authorize_resources
		unless user_signed_in?
   			redirect_to new_user_session_path
   		end
	end

	def get_formatted_status(status)
		case status
		when "initial"
			"&#8605;"
		when "in-progress"
			"&#8608;"
		when "done"
			"&#8607;"
		when "dropped"
			"&#8609;"
		else
			"Undefined"
		end

	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/empty.html.erb
<p class="notice">You do not have any projects yet.</p>
<br /><br />
<%=link_to "Create Your First Project", new_project_path, :class=>"button" %>

app/views/home/home.html.erb
<div class="icons">
<ul>
<li><img src="/assets/icon-1.png" width="108" height="108" alt="" /></li>
<li><img src="/assets/icon-2.png" width="108" height="108" alt="" /></li>
<li><img src="/assets/icon-3.png" width="108" height="108" alt="" /></li>
<li><img src="/assets/icon-4.png" width="108" height="108" alt="" /></li>
</ul>
</div>
<div class="content">
<h1>PLAN  DISCUSS   MANAGE   SUCCESS</h1>
<p>Nucleus is a small project management system built on Ruby on Rails, to help people 
to mange their projects in a simple and effective way. No accounts, no time tracking
just simple SCRUM based planning and divinding process and go. The project 
features high end drag and drop virtual board, discussion rooms and many more..
start from here</p>
</div>

app/views/home/index.html.erb
<section class="comments">
	
	<% @own_projects.each do |p| %>
	<article class="comment">
		<a class="comment-img" href="#non">
			<img src="/assets/<%=p.category%>.png" alt="wse" width="50" height="50" />
		</a>

		<div class="comment-body">
			<div class="text">
			  <p><%=link_to p.name, p %></p>
			</div>
			<p class="attribution"><%=p.users.count%> collaborators, Created at <%=p.created_at.strftime('%A, %b %d, %Y')%>
			</p>
		</div>
		
	</article>
	<% end %>


	<% @projects.each do |p| %>

		<article class="comment">
		<a class="comment-img" href="#non">
			<img src="/assets/<%=p.category%>.png" alt="wse" width="50" height="50" />
		</a>

		<div class="comment-body">
			<div class="text">
			  <p><%=link_to p.name, p %></p>
			</div>
			<p class="attribution">by <b><%=p.author.email%></b>, <%=p.users.count%> collaborators, at <%=p.created_at.strftime('%A, %b %d, %Y')%>
			</p>
		</div>
		
	</article>

	<% end %>

</section>

<aside>
	<h3>Welcome <%=current_user.email %></h3>
	<hr />
	<ul class="mylist">
		<li><b>Authored Projects:</b> <%=@own_projects.count%></li>
		<li><b>Colloborated Projects:</b> <%=@projects.count%></li>
	</ul>
	<br />
	<%=link_to "New Project", new_project_path, :class=>"button" %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nucleus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

   <!--[if lt IE 9]>
   <script src="assets/javascripts/html5shiv-3-respond-1.1.0.min.js"></script>
   <![endif]-->
</head>
<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="wrapper">
  <div class="page">
    <div class="header-container">
      <div class="header">
        <div class="logo"> <a href="/"><img src="/assets/logo.png" width="404" height="86" alt="Nucleus" title="Nucleus" /></a> </div>
        
        <%=render 'shared/header'%>

      </div>
    </div>
    <div class="main-container col1-layout">
      <div class="main">
        <div class="col-main">
          <div class="content-top">
            <div class="content-bottom">
              <div class="content-mid">
               
                <%=yield %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-container">
      <div class="footer">
        <div class="footer-list">
          <ul>
            <li><a href="#">about</a></li>
            <li><a href="#">contact</a></li>
          </ul>
        </div>
        <div class="social-icons"> <span class="share"><img src="/assets/share.gif" width="30" height="79" alt="" /></span>
          <ul>
            <li><a href="#"><img src="/assets/facebook.png" width="57" height="54" alt="facebook" /></a></li>
            <li><a href="#"><img src="/assets/google+.png" width="57" height="54" alt="google+" /></a></li>
            <li><a href="#"><img src="/assets/twitter.png" width="57" height="54" alt="twitter" /></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nucleus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

   <!--[if lt IE 9]>
   <script src="assets/javascripts/html5shiv-3-respond-1.1.0.min.js"></script>
   <![endif]-->
</head>
<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="wrapper">
  <div class="page">
    <div class="header-container">
      <div class="header">
        <div class="logo"> <a href="/"><img src="/assets/logo.png" width="404" height="86" alt="Nucleus" title="Nucleus" /></a> </div>
      </div>
    </div>
    <div class="main-container col1-layout">
      <div class="main">
        <div class="col-main">
          <div class="content-top">
            <div class="content-bottom">
              <div class="content-mid">
                <div class="devise block">
                <%=yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-container">
      <div class="footer">
        <div class="footer-list">
          <ul>
            <li><a href="#">about</a></li>
            <li><a href="#">contact</a></li>
          </ul>
        </div>
        <div class="social-icons"> <span class="share"><img src="/assets/share.gif" width="30" height="79" alt="" /></span>
          <ul>
            <li><a href="#"><img src="/assets/facebook.png" width="57" height="54" alt="facebook" /></a></li>
            <li><a href="#"><img src="/assets/google+.png" width="57" height="54" alt="google+" /></a></li>
            <li><a href="#"><img src="/assets/twitter.png" width="57" height="54" alt="twitter" /></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "description" %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select(:category,[['Ruby', 'ruby'], ['PHP', 'php'], ['Java', 'java'], ['Python', 'python'], ['Design', 'dedign'], ['Other', 'other']]) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %> or 
    <%= link_to 'Cancel', projects_path %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h2>Editing project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Listing projects</h2>
<table class="table">
  <thead>
  <tr>
    <th>Project</th>
    <th>Budget</th>
    <th>Deadline</th>
    <th>Collaborators</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

<% @projects.each do |project| %>
  <tr>
    <td><b><%= project.name %></b><br />
      <p class="dim"><%= project.desc.slice(0..150) %></p></td>
    <td><%= project.cost %></td>
    <td><%= project.deadline.strftime('%A, %b %d') %></td>
    <td>
        <%= project.users.empty? ? "No collaborators" : project.users.count %>
    </td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<article>
<section>
  <%if @project.tasks.empty? %>
    <p class="notice">No tasks created for the project yet.</p>
  <% else %>
    <h2>Stories</h2>
    <%  @project.tasks.each do |t| %>
      <div class="task-block">
      <h4><%=t.name %></h4><span class="pull-right"><%=raw get_formatted_status(t.status) %></span> 
      EST: <%=t.est_days%> days <hr/>
      <%=t.user.email %>
      </div>
      <% end %>
  <% end %>
<div  class="clear"></div>
<h2>Create a new task:</h2>
<%=render "/tasks/form" %>
</section>
</article>
<aside>
<br />
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %> (<%=@project.author.email%>)
</p>

<p>
  <b>Desc:</b>
  <%= @project.desc %>
</p>

<p>
  <b>Cost:</b>
  <%= @project.cost %>
</p>

<p>
  <b>Deadline:</b>
  <%= distance_of_time_in_words(Date.today,@project.deadline) %> remaining
</p>

<p>
  <b>Collaborators:</b>
  <% if @project.users.empty? %>
    No collaborators
  <% else %>
    <% @project.users.each do |u| %>
      <%= u.email %>
    <% end %>
  <% end %>
  <br />

</p>

<hr />

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</aside>

app/views/shared/_header.html.erb
<div class="login-section">
<ul>
<% if user_signed_in? %>
<li><a href="/users/sign_out" data-method="delete" class="button">Sign Out</a></li>
<% else %>
<li>Get Started <a href="/users/sign_up" class="button">Sign Up</a> 
	Already have an account <a href="/users/sign_in" class="button ">Sign In</a></li>
<% end %>
</ul>
</div>

app/views/tasks/_form.html.erb
<% @task = @project.tasks.new %>
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field pull-right">
    <%= f.label "Estimated Days" %><br />
    <%= f.text_field :est_days, :class=>"short" %>
  </div>
  <div class="field pull-left">
    <label>Assign this task</label><br />
    <select data-placeholder="Add a collaborator" class="chosen-select" tabindex="1" name="task[user_id]">
      <% User.all.each do |u| %>
        <option value="<%=u.id%>"><%=u.email%></option>
      <% end %>
    </select>
  </div>
  <hr class="clear"/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Status</th>
    <th>Est days</th>
    <th>Project</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.desc %></td>
    <td><%= task.status %></td>
    <td><%= task.est_days %></td>
    <td><%= task.project %></td>
    <td><%= task.user %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @task.desc %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Est days:</b>
  <%= @task.est_days %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>

<p>
  <b>User:</b>
  <%= @task.user %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>